name: release and push to central
on:
  push:
    branches:
      - refactoring
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Copy files
        working-directory: ${{ env.WORK_DIR }}/
        run: cp -r ./metadata-catalogue/test-data/testinserts.sql "$GITHUB_WORKSPACE/metadata-catalogue/postgis-settings/testinserts.sql"          
      - name: Pre-build
        run: |
          ./initdb.sh
      - name: Docker build
        run: |
          docker build  -f Dockerfile.build  -t epos/metadata-database-deploy-pop-test:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: |
          docker push epos/metadata-database-deploy-pop-test:latest